-- Bonolini OS — BOS Business Intelligence + Autonomy Model, Phase 2:
-- initial pricing Business Rules
--
-- Hand-written, not generated by `drizzle-kit generate` — this migration
-- changes no schema at all (0021 already created every table this one
-- writes to), only data: it seeds the six `category: 'pricing'` Business
-- Rules pricing/rates-provider.ts now reads, each with exactly ONE
-- immediately-`effective` version whose content equals the exact values
-- pricing/service.ts hardcoded before this phase (see
-- pricing/schema.ts's DEFAULT_PRICING_RATES, the single source of truth
-- both this migration and that constant were written from). The system
-- is immediately equivalent to the pre-Phase-2 pricing engine the moment
-- this migration runs — no rule is left unset, no price ever falls back
-- to a guess.
--
-- DEPENDS ON migration 0021 (business_rules/business_rule_versions/
-- business_rule_version_evidence/evidence tables) having already been
-- applied — enforced simply by numeric ordering, same as every other
-- migration in this repository; the migration runner always applies
-- pending files in order.
--
-- Deliberately excludes GetTransfer/Viator: today's pricing engine
-- returns manual_required for both channels unconditionally, with no
-- formula and no constant of any kind (see service.ts's calculatePrice) —
-- there is nothing to seed for them. Inventing a rule for a value that
-- was never hardcoded in the first place would itself violate the "never
-- invent a price" principle this whole system exists to uphold.
--
-- Atomicity: no explicit BEGIN/COMMIT is used because none is needed at
-- two independent levels. (1) The DO block below is, by Postgres's own
-- semantics, a single atomic unit — an unhandled exception inside it
-- (e.g. the tenant lookup failing) rolls back every insert/update it has
-- made so far, automatically, with no partial state ever left behind.
-- (2) `drizzle-kit migrate` additionally wraps this entire file's
-- execution in its own transaction, exactly like every other migration
-- here — the two together mean this file either applies completely or
-- not at all, verified against Postgres's real transactional semantics,
-- not assumed.
--
-- Idempotent: skips any key that already exists for the tenant (a re-run
-- of this same migration, or a rule already created under this exact key
-- by some other means before this ran) — never inserts a duplicate, never
-- overwrites an existing rule's own history.

DO $$
DECLARE
  v_tenant_id uuid;
  v_rule_id uuid;
  v_version_id uuid;
  v_key text;
  v_content jsonb;
BEGIN
  SELECT id INTO v_tenant_id FROM tenants WHERE slug = 'bonolini-transfer';

  IF v_tenant_id IS NULL THEN
    RAISE EXCEPTION 'Phase 2 pricing rules migration: no tenant found with slug ''bonolini-transfer'' — refusing to seed pricing rules for a nonexistent tenant';
  END IF;

  FOR v_key, v_content IN
    SELECT * FROM (VALUES
      ('pricing.minimum_fare', '{"minimumFareCents": 5000}'::jsonb),
      ('pricing.toll_rate', '{"ratePerKm": 0.08}'::jsonb),
      ('pricing.distance_rate', '{"italianUpTo100Km": 1.0, "italianAbove100Km": 0.85, "foreignUpTo100Km": 1.3, "foreignAbove100Km": 1.2}'::jsonb),
      ('pricing.fixed_fare.airport', '{"linateOrioCitta": {"4": 22000, "5": 25000, "6": 28000, "7": 30000, "8": 32000}, "malpensa": {"4": 25000, "5": 27000, "6": 29000, "7": 32000, "8": 35000}}'::jsonb),
      ('pricing.fixed_fare.foreign_tirano', '{"varenna": 26000, "menaggio": 30000, "como": 36000, "milan": 39000, "malpensa": 44000}'::jsonb),
      ('pricing.hospital_waiting.italian', '{"freeMinutes": 60, "ratePerHourCents": 4000}'::jsonb)
    ) AS seed(key, content)
  LOOP
    IF EXISTS (SELECT 1 FROM business_rules WHERE tenant_id = v_tenant_id AND key = v_key) THEN
      CONTINUE;
    END IF;

    INSERT INTO business_rules (id, tenant_id, key, category)
    VALUES (gen_random_uuid(), v_tenant_id, v_key, 'pricing')
    RETURNING id INTO v_rule_id;

    INSERT INTO business_rule_versions (
      id, tenant_id, rule_id, version_number, status, content, author,
      owner_decision, owner_decision_reason, decided_at, effective_from
    )
    VALUES (
      gen_random_uuid(), v_tenant_id, v_rule_id, 1, 'effective', v_content, 'owner',
      'approved',
      'Migrated from the pre-existing hardcoded pricing constant during BOS Business Rules Phase 2 — value unchanged, only its storage location moved from source code to a versioned Business Rule.',
      now(), now()
    )
    RETURNING id INTO v_version_id;

    UPDATE business_rules SET current_version_id = v_version_id, updated_at = now() WHERE id = v_rule_id;
  END LOOP;
END $$;
